// Data type in js

/*=> Primitive data type
1. Number                                      
3. String
4. Boolean
5. Symbol
6. Undefined
7. Null (type is object)*/


// ----------------------------------------------------------------------
// 1. number - integer,float

let a = 10;
console.log(typeof a);

let num = 12;
console.log(typeof num);

const tejas = 15;
console.log(typeof num);

console.log(
    `Number type min value is ${Number.MAX_VALUE} and max value is ${Number.MIN_VALUE}`);

//-----------------------------------------------------------------------

// String -  Any data under single quote, double quote or backtick quote - 
//string is a coection of charater


let myname = "tejas";
console.log(typeof myname);

a = "tejas gojariya";
console.log(typeof a);

// Booleans - true or false value

let ismobile = true;
console.log(typeof ismobile);

t = false;
console.log(typeof t);


// Null - empty value or no value

let x = null;
console.log(null == x); // return true
console.log(typeof null);

let p = null;
console.log(null === 0); // return false
console.log(typeof null);

// Undefined - a declared variable without a value
// undefined -> absence of value

let g;
console.log(typeof g);

// symbol - A unique value that can be generated by Symbol constructor
let h = Symbol("tejas");
let k = Symbol("tejas");
console.log(`h ===k ${h == k}`);
console.log(h.valueOf == k.valueOf);

let age = 19;
age > 12 ? console.log("You can vote") : console.log("you can not vote");